language: cpp
cache: ccache
before_install:
  - sudo apt-get install -y mesa-utils freeglut3-dev 
addons:
  apt:
    update: true
    packages: 
      - cmake
      - cmake-data
script: mkdir build && cd build && cmake .. && make