#ifndef _BASIC_GL_ELEMENTs_H_
#define _BASIC_GL_ELEMENTS_H_

namespace BasicGL
{
    enum Elements { CONTAINER = 0, POINT, LINE, POLYGON, TRIANGLE, RECTANGLE, CIRCLE, SEQUENCE, LOOP, CONNECTED_TRIANGLES, RADIAL_TRIANGLES, CONNECTED_RECTANGLES, SPHERE, CONE, CUBE, CYLINDER, TEAPOT, TEXT, OBJECT };
}

#endif
